// GENERATED by scripts/generate-movement-figures.py — do not edit.
// One line figure per movement (ADR-0013). Rendered as white
// silhouettes so the UI tints them to the theme's accent.

import type { ImageSourcePropType } from "react-native";

export const movementFigures: Record<string, ImageSourcePropType> = {
  "wall-push-up": require("../../assets/movements/wall-push-up.png"),
  "wide-wall-push-up": require("../../assets/movements/wide-wall-push-up.png"),
  "wall-push-up-hold": require("../../assets/movements/wall-push-up-hold.png"),
  "incline-push-up": require("../../assets/movements/incline-push-up.png"),
  "wide-incline-push-up": require("../../assets/movements/wide-incline-push-up.png"),
  "incline-push-up-hold": require("../../assets/movements/incline-push-up-hold.png"),
  "kneeling-push-up": require("../../assets/movements/kneeling-push-up.png"),
  "wide-kneeling-push-up": require("../../assets/movements/wide-kneeling-push-up.png"),
  "incline-pike-push-up": require("../../assets/movements/incline-pike-push-up.png"),
  "full-push-up": require("../../assets/movements/full-push-up.png"),
  "pike-push-up": require("../../assets/movements/pike-push-up.png"),
  "decline-push-up": require("../../assets/movements/decline-push-up.png"),
  "archer-push-up": require("../../assets/movements/archer-push-up.png"),
  "shoulder-blade-squeeze": require("../../assets/movements/shoulder-blade-squeeze.png"),
  "wall-slide": require("../../assets/movements/wall-slide.png"),
  "prone-w-raise": require("../../assets/movements/prone-w-raise.png"),
  "doorframe-lean-row": require("../../assets/movements/doorframe-lean-row.png"),
  "prone-y-raise": require("../../assets/movements/prone-y-raise.png"),
  "doorframe-row": require("../../assets/movements/doorframe-row.png"),
  "prone-y-t-w-raise": require("../../assets/movements/prone-y-t-w-raise.png"),
  "deep-doorframe-row": require("../../assets/movements/deep-doorframe-row.png"),
  "single-arm-doorframe-row": require("../../assets/movements/single-arm-doorframe-row.png"),
  "single-arm-doorframe-row-pause": require("../../assets/movements/single-arm-doorframe-row-pause.png"),
  "supported-sit-to-stand": require("../../assets/movements/supported-sit-to-stand.png"),
  "high-wall-sit": require("../../assets/movements/high-wall-sit.png"),
  "partial-squat": require("../../assets/movements/partial-squat.png"),
  "sit-to-stand": require("../../assets/movements/sit-to-stand.png"),
  "wall-sit": require("../../assets/movements/wall-sit.png"),
  "half-squat": require("../../assets/movements/half-squat.png"),
  "air-squat": require("../../assets/movements/air-squat.png"),
  "sumo-squat": require("../../assets/movements/sumo-squat.png"),
  "paused-squat": require("../../assets/movements/paused-squat.png"),
  "split-squat": require("../../assets/movements/split-squat.png"),
  "reverse-lunge": require("../../assets/movements/reverse-lunge.png"),
  "elevated-split-squat": require("../../assets/movements/elevated-split-squat.png"),
  "single-leg-sit-to-stand": require("../../assets/movements/single-leg-sit-to-stand.png"),
  "glute-bridge": require("../../assets/movements/glute-bridge.png"),
  "glute-bridge-hold": require("../../assets/movements/glute-bridge-hold.png"),
  "standing-hip-hinge": require("../../assets/movements/standing-hip-hinge.png"),
  "glute-bridge-march": require("../../assets/movements/glute-bridge-march.png"),
  "paused-glute-bridge": require("../../assets/movements/paused-glute-bridge.png"),
  "hinge-and-reach": require("../../assets/movements/hinge-and-reach.png"),
  "single-leg-glute-bridge": require("../../assets/movements/single-leg-glute-bridge.png"),
  "feet-elevated-glute-bridge": require("../../assets/movements/feet-elevated-glute-bridge.png"),
  "single-leg-hip-hinge": require("../../assets/movements/single-leg-hip-hinge.png"),
  "hip-thrust": require("../../assets/movements/hip-thrust.png"),
  "single-leg-elevated-bridge": require("../../assets/movements/single-leg-elevated-bridge.png"),
  "single-leg-hip-thrust": require("../../assets/movements/single-leg-hip-thrust.png"),
  "wall-plank": require("../../assets/movements/wall-plank.png"),
  "seated-knee-lift": require("../../assets/movements/seated-knee-lift.png"),
  "lying-heel-slide": require("../../assets/movements/lying-heel-slide.png"),
  "incline-plank": require("../../assets/movements/incline-plank.png"),
  "kneeling-balance-reach": require("../../assets/movements/kneeling-balance-reach.png"),
  "lying-heel-tap": require("../../assets/movements/lying-heel-tap.png"),
  "knee-plank": require("../../assets/movements/knee-plank.png"),
  "knee-side-plank": require("../../assets/movements/knee-side-plank.png"),
  "full-plank": require("../../assets/movements/full-plank.png"),
  "side-plank": require("../../assets/movements/side-plank.png"),
  "plank-shoulder-tap": require("../../assets/movements/plank-shoulder-tap.png"),
  "plank-walkout": require("../../assets/movements/plank-walkout.png"),
};

/** The figure for a movement, or null when one is missing (a
 *  degraded build renders the name alone rather than a hole). */
export function movementFigure(
  movementId: string,
): ImageSourcePropType | null {
  return movementFigures[movementId] ?? null;
}
