// GENERATED by scripts/generate-voice-audio.mjs — do not edit.
// One spoken file per unique coaching cue, keyed by the cue's exact text
// so the player looks up the line it is already showing. Empty until the
// owner runs the generator with the chosen voice; the app builds either
// way and voice simply has nothing to say.
import type { AudioSource } from "expo-audio";

export const voiceCues: Record<string, AudioSource> = {

};

/** The spoken file for a cue, or null when none was generated. */
export function voiceCue(cue: string): AudioSource | null {
  return voiceCues[cue] ?? null;
}

/** Whether ANY spoken cue is bundled — the Settings card's existence. */
export function hasVoiceAudio(): boolean {
  return Object.keys(voiceCues).length > 0;
}
