import { Image, StyleSheet, View } from "react-native";

import { useTheme } from "../theme";

// The drawn mark — the pose-1 stretching figure making the F — as the
// app renders it. A white silhouette tinted to the theme's accent, the
// same mechanism as every movement figure, so one asset is right in both
// themes. Generated by scripts/generate-brand-assets.py alongside the
// icon set: it regenerates rather than drifts.
//
// Decorative: the headline beside it carries the brand words, and the
// wordmark on sign-in is the header a screen reader lands on.

const source = require("../../../assets/brand/mark.png");

type MarkSize = "hero";

const DIMENSIONS: Record<MarkSize, number> = {
  hero: 160,
};

interface BrandMarkProps {
  size?: MarkSize;
  testID?: string;
}

export function BrandMark({ size = "hero", testID }: BrandMarkProps) {
  const colors = useTheme();
  const box = DIMENSIONS[size];
  return (
    <View
      testID={testID}
      accessibilityElementsHidden
      importantForAccessibility="no-hide-descendants"
      style={[styles.frame, { width: box, height: box }]}
    >
      <Image
        source={source}
        resizeMode="contain"
        style={[styles.image, { tintColor: colors.accent }]}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  frame: {
    alignItems: "center",
    justifyContent: "center",
  },
  image: {
    width: "100%",
    height: "100%",
  },
});
